"""Local-file-input support for cdif-xas-UKDS.

Adds two capabilities so the pipeline can run against XDI files on the
local disk, with no Dataverse instance available:

  1. is_local_path / read_local_xdi — detect file:// URIs or absolute
     paths and read the XDI text off disk, packaged as a Response-like
     object that CDI_DDI.parse_xdi can consume.
  2. build_placeholder_dataset — generate a minimal schema.org Dataset
     rdflib graph with placeholder values for the fields normally
     supplied by Dataverse's ?exporter=schema.org export
     (identifier, name, dateModified, license, distribution).

The placeholder Dataset uses:
  - @id: urn:local:xdi:{stem} where {stem} is the XDI file name w/o suffix
  - schema:name: file stem
  - schema:description: notes it is placeholder metadata
  - schema:identifier: local:{stem}
  - schema:dateModified / datePublished: file mtime, ISO 8601 date
  - schema:license: https://creativecommons.org/licenses/by/4.0/
    (CDIF metadata default; distinct from any license on the XAS data
    itself, which is not known in local mode)
  - schema:distribution: a DataDownload with contentUrl pointing at
    the file:// URI of the local file, encodingFormat application/x-xdi

Downstream RML mapping and framing pipelines can consume this graph the
same way they consume the Dataverse-sourced enrichment.
"""
from __future__ import annotations

import datetime
from pathlib import Path
from types import SimpleNamespace

import rdflib


SCHEMA_NS = rdflib.Namespace("http://schema.org/")
# The RML mapping's TriplesMap iterators match dataset @ids of the shape
# http://localhost:8080/citation?persistentId=perma:DV/...  (Dataverse's
# local-dev citation URL). Mimic that shape so local runs feed the RML
# pipeline without touching the mapping regexes.
_ID_PREFIX = "http://localhost:8080/citation?persistentId=perma:DV/"


def is_local_path(url: str) -> bool:
    """True if the URL string points at a local file (file:// scheme,
    absolute POSIX path, or Windows drive-letter path).
    """
    if not url:
        return False
    if url.startswith("file://"):
        return True
    if url.startswith("/"):
        return True
    if len(url) > 1 and url[1] == ":":
        # Windows drive letter (C:\..., c:/...)
        return True
    return False


def _local_path_from_url(url: str) -> Path:
    """Strip file:// prefix, return a Path."""
    stripped = url.removeprefix("file://")
    # file:///C:/path on Windows leaves an unwanted leading /
    if len(stripped) > 2 and stripped[0] == "/" and stripped[2] == ":":
        stripped = stripped[1:]
    return Path(stripped)


def read_local_xdi(url: str) -> SimpleNamespace:
    """Read an XDI file off disk. Returns a Response-like object with a
    `.text` attribute so it can substitute for requests.Response in
    api/cdi.py:CDI_DDI.
    """
    path = _local_path_from_url(url)
    if not path.exists():
        raise FileNotFoundError(f"Local XDI file not found: {path}")
    return SimpleNamespace(text=path.read_text(encoding="utf-8"),
                           _local_path=path)


def build_placeholder_dataset(url: str,
                              dataset_iri: str | None = None) -> rdflib.Graph:
    """Generate the schema.org Dataset graph normally provided by
    Dataverse's ?exporter=schema.org export, using local-file-derived
    placeholder values.

    Merged into cdi_graph in api/cdi.py:generate_cdi when the input is a
    local path. Fields chosen to satisfy the xasDocument/1.0 profile's
    Core-tier minimum (identifier, name, dateModified, license, and
    either url or distribution).
    """
    path = _local_path_from_url(url)
    stem = path.stem or "local-xdi"

    g = rdflib.Graph()
    g.bind("schema", SCHEMA_NS)

    ds = rdflib.URIRef(dataset_iri or f"{_ID_PREFIX}{stem}")

    g.add((ds, rdflib.RDF.type, SCHEMA_NS.Dataset))
    g.add((ds, SCHEMA_NS.name, rdflib.Literal(stem)))
    g.add((ds, SCHEMA_NS.description, rdflib.Literal(
        "Placeholder metadata generated by cdif-xas-UKDS local pipeline. "
        "Values normally sourced from Dataverse are stubbed; edit "
        "downstream if you need real values."
    )))
    g.add((ds, SCHEMA_NS.identifier, rdflib.Literal(f"local:{stem}")))

    # Dates from file mtime, ISO 8601 date-only. Typed as schema:Date so
    # the JSON-LD serialization carries a {"@type": "schema:Date",
    # "@value": "..."} shape; the RML mapping reads
    # $['schema:dateModified']['@value'], so a plain-literal date would
    # not be picked up.
    try:
        mtime = datetime.datetime.fromtimestamp(
            path.stat().st_mtime, tz=datetime.timezone.utc
        )
        date_str = mtime.date().isoformat()
    except OSError:
        date_str = datetime.date.today().isoformat()
    date_typed = rdflib.Literal(date_str, datatype=SCHEMA_NS.Date)
    g.add((ds, SCHEMA_NS.dateModified, date_typed))
    g.add((ds, SCHEMA_NS.datePublished, date_typed))

    # Default CDIF metadata license
    g.add((ds, SCHEMA_NS.license,
           rdflib.URIRef("https://creativecommons.org/licenses/by/4.0/")))

    # Distribution: the local file itself
    dist = rdflib.URIRef(f"{_ID_PREFIX}{stem}#distribution")
    g.add((ds, SCHEMA_NS.distribution, dist))
    g.add((dist, rdflib.RDF.type, SCHEMA_NS.DataDownload))
    try:
        content_url = path.resolve().as_uri()
    except (OSError, ValueError):
        content_url = f"file://{path}"
    g.add((dist, SCHEMA_NS.contentUrl, rdflib.URIRef(content_url)))
    g.add((dist, SCHEMA_NS.encodingFormat,
           rdflib.Literal("application/x-xdi")))
    g.add((dist, SCHEMA_NS.name, rdflib.Literal(path.name)))

    return g
